<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>mptc.seangleng</groupId>
        <artifactId>order-service-domain</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <!--Critical logic module -->
    <artifactId>order-domain-core</artifactId>

    <!--How we import common to dependency to other module without version, the version will be followed to parent-->
    <dependencies>
        <dependency>
            <groupId>mptc.seangleng</groupId>
            <artifactId>common-domain</artifactId>
        </dependency>
    </dependencies>

</project>